// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: keyauth.proto

package keyauthpb

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on Authenticator with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *Authenticator) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Authenticator with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in AuthenticatorMultiError, or
// nil if none found.
func (m *Authenticator) ValidateAll() error {
	return m.validate(true)
}

func (m *Authenticator) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for FromHeader

	// no validation rules for FromParam

	if len(errors) > 0 {
		return AuthenticatorMultiError(errors)
	}

	return nil
}

// AuthenticatorMultiError is an error wrapping multiple validation errors
// returned by Authenticator.ValidateAll() if the designated constraints
// aren't met.
type AuthenticatorMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m AuthenticatorMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m AuthenticatorMultiError) AllErrors() []error { return m }

// AuthenticatorValidationError is the validation error returned by
// Authenticator.Validate if the designated constraints aren't met.
type AuthenticatorValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e AuthenticatorValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e AuthenticatorValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e AuthenticatorValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e AuthenticatorValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e AuthenticatorValidationError) ErrorName() string { return "AuthenticatorValidationError" }

// Error satisfies the builtin error interface
func (e AuthenticatorValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sAuthenticator.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = AuthenticatorValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = AuthenticatorValidationError{}

// Validate checks the field values on KeyAuth with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *KeyAuth) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on KeyAuth with the rules defined in the
// proto definition for this message. If any rules are violated, the result is
// a list of violation errors wrapped in KeyAuthMultiError, or nil if none found.
func (m *KeyAuth) ValidateAll() error {
	return m.validate(true)
}

func (m *KeyAuth) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	{
		sorted_keys := make([]string, len(m.GetAuthenticators()))
		i := 0
		for key := range m.GetAuthenticators() {
			sorted_keys[i] = key
			i++
		}
		sort.Slice(sorted_keys, func(i, j int) bool { return sorted_keys[i] < sorted_keys[j] })
		for _, key := range sorted_keys {
			val := m.GetAuthenticators()[key]
			_ = val

			// no validation rules for Authenticators[key]

			if all {
				switch v := interface{}(val).(type) {
				case interface{ ValidateAll() error }:
					if err := v.ValidateAll(); err != nil {
						errors = append(errors, KeyAuthValidationError{
							field:  fmt.Sprintf("Authenticators[%v]", key),
							reason: "embedded message failed validation",
							cause:  err,
						})
					}
				case interface{ Validate() error }:
					if err := v.Validate(); err != nil {
						errors = append(errors, KeyAuthValidationError{
							field:  fmt.Sprintf("Authenticators[%v]", key),
							reason: "embedded message failed validation",
							cause:  err,
						})
					}
				}
			} else if v, ok := interface{}(val).(interface{ Validate() error }); ok {
				if err := v.Validate(); err != nil {
					return KeyAuthValidationError{
						field:  fmt.Sprintf("Authenticators[%v]", key),
						reason: "embedded message failed validation",
						cause:  err,
					}
				}
			}

		}
	}

	for idx, item := range m.GetRules() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, KeyAuthValidationError{
						field:  fmt.Sprintf("Rules[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, KeyAuthValidationError{
						field:  fmt.Sprintf("Rules[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return KeyAuthValidationError{
					field:  fmt.Sprintf("Rules[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return KeyAuthMultiError(errors)
	}

	return nil
}

// KeyAuthMultiError is an error wrapping multiple validation errors returned
// by KeyAuth.ValidateAll() if the designated constraints aren't met.
type KeyAuthMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m KeyAuthMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m KeyAuthMultiError) AllErrors() []error { return m }

// KeyAuthValidationError is the validation error returned by KeyAuth.Validate
// if the designated constraints aren't met.
type KeyAuthValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e KeyAuthValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e KeyAuthValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e KeyAuthValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e KeyAuthValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e KeyAuthValidationError) ErrorName() string { return "KeyAuthValidationError" }

// Error satisfies the builtin error interface
func (e KeyAuthValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sKeyAuth.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = KeyAuthValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = KeyAuthValidationError{}
